import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import MainLayout from '../components/MainLayout'
import Banner from '../components/Banner'
import Products from '../components/Products'
import { Button } from 'reactstrap'
import { faChevronDown } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

export default function Home() {
    return (
        <div className="home-page">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.guide}>
                <div className={styles['guide-btn']}>
                    <div className={styles['guide-btn__title']}>Guide tour</div>
                    {/* <FontAwesomeIcon icon={faChevronDown} /> */}
                    {/* <i className="fas fa-chevron-down"></i> */}
                </div>
            </div>
            <MainLayout>
                <Banner />
                <Products />
            </MainLayout>
        </div>
    )
}
